//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("Eugen (WebDucer) Richter")]
[assembly: AssemblyCopyright("MIT - (c) 2018 Eugen [WebDucer] Richter")]

// Metadata Attributes
[assembly: AssemblyMetadata("git_hash", "610452664adc04d42c4e778619c3673612e82460")]
[assembly: AssemblyMetadata("sem_ver", "0.1.1")]
[assembly: AssemblyMetadata("build_date", "2018-06-30")]
